### ISSUE TITLE
WPbakery

### ISSUE THREAD

**Issue by dusta** [poweredcache/powered-cache#64] opened 2021-10-06 16:11 UTC
This option is not showing when is installed WPbakery editor. 
https://docs.poweredcache.com/disable-page-caching-for-specific-posts/

**Comment by mustafauysal** [comment] 2021-10-20 23:21
@dusta Can you add a screenshot? and check the console logs? 

Do you see the options when not using WPBaker' editing mode?

**Comment by mustafauysal** [comment] 2021-10-31 09:35
I assume the problem is solved, closing this issue now, feel free to re-open if the latest version didn't work for you.

**Closed by mustafauysal** 2021-10-31 09:35 UTC
